// commands/pies.js
const fetch = require('node-fetch');
const { channelInfo } = require('../lib/messageConfig');

const BASE = 'https://shizoapi.onrender.com/api/pies';
const VALID_COUNTRIES = ['china', 'indonesia', 'japan', 'korea', 'hijab'];

async function fetchPiesImageBuffer(country) {
  const url = `${BASE}/${country}?apikey=shizo`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const contentType = res.headers.get('content-type') || '';
  if (!contentType.includes('image')) throw new Error('API tidak mengembalikan gambar');
  return res.buffer();
}

async function piesCommand(sock, chatId, message, args) {
  const sub = (args && args[0] ? args[0] : '').toLowerCase();

  // Bantuan penggunaan
  if (!sub) {
    const txt = [
      '╭─〔 🥧 *PIES GENERATOR* 〕',
      '│ 📸 *Generate gambar AI Pies*',
      '│',
      '│ 📌 *Cara pakai:* `.pies <country>`',
      '│ 🌍 *Country tersedia:*',
      `│ ${VALID_COUNTRIES.join(', ')}`,
      '╰──────────────────────────────',
      '✨ *Andika Bot*'
    ].join('\n');
    await sock.sendMessage(chatId, { text: txt, ...channelInfo }, { quoted: message });
    return;
  }

  // Validasi country
  if (!VALID_COUNTRIES.includes(sub)) {
    await sock.sendMessage(chatId, {
      text: `❌ *Negara tidak didukung:* ${sub}\n✅ *Coba salah satu:* ${VALID_COUNTRIES.join(', ')}`,
      ...channelInfo
    }, { quoted: message });
    return;
  }

  try {
    const imageBuffer = await fetchPiesImageBuffer(sub);
    await sock.sendMessage(
      chatId,
      {
        image: imageBuffer,
        caption: [
          '╭─〔 🥧 *PIES RESULT* 〕',
          `│ 🌍 Country: *${sub.toUpperCase()}*`,
          '╰──────────────────────────────',
          '✨ *Generated by Andika Bot*'
        ].join('\n'),
        ...channelInfo
      },
      { quoted: message }
    );
  } catch (err) {
    console.error('❌ Error in pies command:', err);
    await sock.sendMessage(chatId, {
      text: '❌ *Gagal mengambil gambar Pies.*\nCoba lagi nanti ya!',
      ...channelInfo
    }, { quoted: message });
  }
}

async function piesAlias(sock, chatId, message, country) {
  try {
    const imageBuffer = await fetchPiesImageBuffer(country);
    await sock.sendMessage(
      chatId,
      {
        image: imageBuffer,
        caption: [
          '╭─〔 🥧 *PIES RESULT* 〕',
          `│ 🌍 Country: *${country.toUpperCase()}*`,
          '╰──────────────────────────────',
          '✨ *Generated by Andika Bot*'
        ].join('\n'),
        ...channelInfo
      },
      { quoted: message }
    );
  } catch (err) {
    console.error(`Error in pies alias (${country}) command:`, err);
    await sock.sendMessage(chatId, {
      text: '❌ *Gagal mengambil gambar.* Coba lagi nanti ya!',
      ...channelInfo
    }, { quoted: message });
  }
}

module.exports = { piesCommand, piesAlias, VALID_COUNTRIES };
