// commands/sora.js
const axios = require('axios');
const { channelInfo } = require('../lib/messageConfig');

async function soraCommand(sock, chatId, message) {
  try {
    // ambil teks utama & quoted
    const rawText =
      message.message?.conversation?.trim() ||
      message.message?.extendedTextMessage?.text?.trim() ||
      message.message?.imageMessage?.caption?.trim() ||
      message.message?.videoMessage?.caption?.trim() ||
      '';

    const used = (rawText || '').split(/\s+/)[0] || '.sora';
    const args = rawText.slice(used.length).trim();

    const quoted = message.message?.extendedTextMessage?.contextInfo?.quotedMessage;
    const quotedText =
      quoted?.conversation ||
      quoted?.extendedTextMessage?.text ||
      quoted?.imageMessage?.caption ||
      quoted?.videoMessage?.caption ||
      '';

    const input = args || quotedText;

    if (!input) {
      await sock.sendMessage(
        chatId,
        {
          text: '✍️ *Masukkan prompt videonya dulu ya!*\n\nContoh:\n`.sora anime girl flying with wings in cyberpunk city`',
          ...channelInfo,
        },
        { quoted: message }
      );
      return;
    }

    // Kirim tanda sedang proses
    await sock.sendMessage(chatId, { react: { text: '🎥', key: message.key } });

    // API utama (OpenSora style)
    const apiUrl = `https://okatsu-rolezapiiz.vercel.app/ai/txt2video?text=${encodeURIComponent(input)}`;
    const { data } = await axios.get(apiUrl, {
      timeout: 60000,
      headers: { 'user-agent': 'Mozilla/5.0 (AndikaBot)' },
    });

    const videoUrl = data?.videoUrl || data?.result || data?.data?.videoUrl;
    if (!videoUrl) throw new Error('Video tidak ditemukan dari API.');

    const senderJid = message.key.participant || message.key.remoteJid || '';
    const senderMention = senderJid ? `@${senderJid.split('@')[0]}` : '';

    const caption =
`╭─〔 🎬 *SORA AI VIDEO GENERATOR* 〕
│ 🧠 *Prompt:* ${input}
│ 👤 Dibuat oleh: ${senderMention}
│ ⏱️ Estimasi proses: ± beberapa detik
╰──────────────────────────
✨ _Generated by Andika Bot_`;

    await sock.sendMessage(
      chatId,
      {
        video: { url: videoUrl },
        mimetype: 'video/mp4',
        caption,
        mentions: senderJid ? [senderJid] : [],
        ...channelInfo,
      },
      { quoted: message }
    );
  } catch (error) {
    console.error('[SORA ERROR]:', error?.message || error);
    await sock.sendMessage(
      chatId,
      {
        text: '❌ *Gagal membuat video dari prompt ini.*\nCoba gunakan deskripsi yang lebih jelas atau ganti kata kunci.',
        ...channelInfo,
      },
      { quoted: message }
    );
  }
}

module.exports = soraCommand;
